### ISSUE TITLE
lighthouse page speed performance report "passive listeners"

### ISSUE THREAD

**Issue by nfsarmento** [alvarotrigo/pagePiling.js#215]
Thank you for making this available and free to everyone.

When running Google PageSpeed insights have the warning below. It is possible to fix it?

"Does not use passive listeners to improve scrolling performance
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance."

**Comment by alvarotrigo** [comment]
Yeah there's nothing to worry about. That's just a warning that's why the error uses the word "consider" :)

As can be read [on the docs](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools) pointed out by the "Learn more" link on the error, passive event listeners are used to indicate the browser that our event listener won't be preventing the scroll:

> Passive event listeners solve this problem by letting you indicate that an event listener will never prevent scrolling.

However pagePiling.js works by preventing the default scroll behaviour and therefore it needs to prevent both touch and scroll events.
